version: "3"
services:
  redis:
    image: library/redis:5.0
    container_name: quant_redis
    restart: always
    command: /bin/bash -c "/usr/bin/redis-server"
    user: root
    volumes:
      - "./redis/redis.conf:/etc/redis/redis.conf"
    links:
      - backend


  mysql:
    image: library/mysql:5.7
    container_name: quant_mysql
    restart: always
    environment:
      MYSQL_USER: 'mgw'
      MYSQL_PASSWORD: 'mgw'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'quant_platform'
    ports:
      - 3306:3306
    volumes:
      - "./mysql/db:/var/lib/mysql"
      - "./mysql/conf:/etc/my.cnf"
      - "./mysql/logs:/var/log/mysql/"
      - "./mysql/init:/docker-entrypoint-initdb.d/"
    links:
      - backend


  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: quant_backend
    restart: always
    volumes:
      - ".:/quant_platform"
    depends_on:
      - mysql
      - redis
    links:
      - mysql
      - redis


  nginx:
    image: nginx:3.3
    container_name: quant_nginx
     command: /bin/bash -c "envsubst < /etc/nginx/conf.d/ > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    ports:
    - 8000:80
    links:
      - backend
